version: 1
disable_existing_loggers: False
formatters:
        simple:
            format: "%(asctime)s %(levelname)s %(message)s"
handlers:
    console:
            class: logging.StreamHandler
            level: DEBUG
            formatter: simple
            stream: ext://sys.stdout
    info_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: INFO
            formatter: simple
            filename: ./../../log/info.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
    warning_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: WARNING
            formatter: simple
            filename: ./../../log/warning.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
    error_file_handler:
            class: logging.handlers.RotatingFileHandler
            level: ERROR
            formatter: simple
            filename: ./../../log/errors.log
            maxBytes: 10485760
            backupCount: 20
            encoding: utf8
loggers:
    my_module:
            level: ERROR
            handlers: [info_file_handler]
            propagate: no
root:
    level: INFO
    handlers: [console,info_file_handler, warning_file_handler, error_file_handler]